# NixOS VM test: verify the NeoForge server starts with all mods via the clan module
{
  pkgs,
  nixosLib,
  clan-core,
  self,
  drasl,
}:
nixosLib.runTest (
  { ... }:
  {
    imports = [
      clan-core.modules.nixosTest.clanTest
    ];

    hostPkgs = pkgs;

    name = "server-start";

    clan = {
      directory = ./.;
      test.useContainers = false;

      modules."@numtide/numcraft" = import ../../clan-module.nix { inherit self drasl; };

      inventory = {
        machines.server = { };

        instances."numcraft" = {
          module.name = "@numtide/numcraft";
          module.input = "self";

          roles.default.machines.server = {
            settings = {
              slackChannelId = "C000000000";
              slackUserMapping = {
                "U000000000" = "testuser";
              };
            };
          };
        };
      };
    };

    nodes.server = { pkgs, ... }: {
      environment.systemPackages = [ pkgs.mcrcon ];
      virtualisation.memorySize = 4096;
    };

    testScript = ''
      start_all()
      server.wait_for_unit("minecraft-server")
      server.wait_for_open_port(25575)

      # Read the RCON password that was generated by clan vars and patched into server.properties
      password = server.succeed(
          "grep '^rcon.password=' /var/lib/minecraft/server.properties | cut -d= -f2"
      ).strip()

      server.succeed(
          f"mcrcon -H localhost -P 25575 -p '{password}' -c 'seed'"
      )

      server.succeed("systemctl stop minecraft-server")
    '';
  }
)
